### PR TITLE
debug makefile

### PR DESCRIPTION
**Pull request by hannesdatta**
replace R CMD BATCH by RScript - RScript stops if it encounters an error, while R CMD BATCH doesn't throw errors. Bad for students learning whether make works or not...

I'm using your template in my class right now, would be fantastic to accept my changes!

### CODE REVIEW

**Review by rgreminger — CHANGES_REQUESTED** [review]
Good point, but I think it should be `Rscript` instead of `RScript`.  
I don't seem to be able to adjust this myself in the pull request. Once it's adjusted I can accept the changes

**Comment by rgreminger** [comment]
Good point @hannesdatta, thanks!
I now also managed to update your pull request fixing it from `RScript` to `Rscript`, so ignore my previous review.

**Comment by rgreminger** [comment]
@hannesdatta Final note. Lower/upper case only matters for Linux (and potentially Mac)

**Comment by hannesdatta** [comment]
amazing, thanks a bunch, rafael!

**Pull request merged**
